import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D
from sklearn.metrics import accuracy_score
from autograd import grad
from sklearn import datasets
from sklearn.model_selection import train_test_split
from numpy.linalg import pinv